version: "3"

services:
  grpc_server_service:
    build:
      context: .
      dockerfile: Dockerfile-server
    ports: # just for debugging
      - "50051:50051"

  envoy_service:
    build:
      context: .
      dockerfile: Dockerfile-envoy
    ports:
      - "8000:8000"
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
